### ISSUE TITLE
Allow on-board a package from URL

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-cli#26]
Would be nice to on-board a package from URL. That allow us to not download the package from github to upload but do this automatically having the artifacts in github,

Current way:
```
tng-cli -u eu.5gtango.ns-mediapilot-service-k8s.0.3.tgo
```
Aditional way:
```
tng-cli -u https://github.com/sonata-nfv/tng-media-pilot/blob/master/packages/eu.5gtango.ns-mediapilot-service-hybrid.0.1.tgo
```

**Comment by tsoenen** [comment]
Done
